manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: bobobo1618
      url-base: https://github.com/bobobo1618/zephyr.git
  projects:
    - name: zmk-bobobo1618
      remote: bobobo1618
      revision: fix-oled
      clone-depth: 1
      import: app/west.yml
  self:
    path: config
